version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    restart: unless-stopped
    ports: 
      - ${REDIS_PORT}:6379
    volumes:
      - ./.data/redis:/data

  bot:
    build: .
    image: ${BOT_NAME}:${BOT_VERSION}
    restart: unless-stopped
    environment:
      # mandatory ENVs
      - API_ID
      - API_HASH
      - BOT_NAME
      - BOT_TOKEN
      - BOT_VERSION
      - DB_PASSWORD
      - SMP_APP_ID
      - SMP_APP_SECRET
      - SMP_BASE_URL
      - SUPPORT_CHAT_URL
      - INSTAGRAM_RAPIDAPI_KEY
      - TIKTOK_RAPIDAPI_KEY
      # optional ENVs
      - ANNOUNCE_DELAY_S
      - ANNOUNCE_DELAY_BETWEEN_ANNOUNCES_H
      - ANNOUNCE_INTERVAL_S
      - ANNOUNCE_FEEDBACK_INTERVAL_S
      - ANNOUNCE_PACK_LENGTH
      - ANNOUNCE_WORKERS
      - TELEGRAM_FLOOD_CONTROL_PAUSE_S
      - TROTTLING_WAIT_BETWEEN_PAID_REQUESTS_S
      - TROTTLING_WAIT_BETWEEN_REQUESTS_S
      # debug ENVs
      - LOG_LEVEL
      - SEND_PLATFORM_METRICS_DATA
    tty: true
