version: '3.8'

services:
  redis:
    image: redis:3.2
    restart: unless-stopped
    ports: 
      - ${REDIS_PORT}:6379
    volumes:
      - ./.data/redis:/data

  bot:
    build: .
    image: ${BOT_NAME}:${BOT_VERSION}
    restart: unless-stopped
    environment:
      # mandatory ENVs
      - API_ID
      - API_HASH
      - BOT_NAME
      - BOT_TOKEN
      - BOT_VERSION
      - DB_PASSWORD
      - SUPPORT_CHAT_URL
      - RAPIDAPI_KEY
      # optional ENVs
      - TELEGRAM_FLOOD_CONTROL_PAUSE_S
      - TROTTLING_WAIT_BETWEEN_PAID_REQUESTS_S
      - TROTTLING_WAIT_BETWEEN_REQUESTS_S
      # debug ENVs
      - LOG_LEVEL
    tty: true
