---
# Ш А Б Л О Н
# описание полей см. в README

# имя модуля:
#   <<: *common
#   allowed_role:
#   command:
#   description:
#   friendly_name:
#   icon:
#   introduction_text:
#
#   <<: *csv, <<: *hashtags_editor и т.д. добавлять, если данные фичи есть в модуле

# ----- Общие поля -----
common: &common
  current_module_text: Вы находитесь в модуле {}.
  help_command_text: Для возврата в меню нажмите /start.
  unknown_command_text: Такой команды не существует. Воспользуйся меню под строкой ввода, чтобы попробовать доступный функционал.
  unhandled_error_text: Что-то пошло не так. Но поддержка рядом! /support
  wrong_input_text: Это не похоже на слово.

api_adapter:
  <<: *common
  error_text_media_not_found: Мне не удалось найти медиа по данной ссылке. Проверьте корректность ссылки и повторите попытку.
  error_text_account_not_found: Мне не удалось найти этот аккаунт. Проверьте корректность написания никнейма или ссылки и повторите попытку.
  error_text_account_private: К сожалению, аккаунт, который вы отправили на анализ, является закрытым. Я могу анализировать только открытые аккаунты.
  error_text_first_provider_failed: |
      Наблюдаю проблемы с доступом к сервису. 
      Возможно, придется подождать дольше обычного...

trottling:
  <<: *common
  warning_message: |
    Вы отправили слишком много запросов, пожалуйста, подождите.
    Повторные запросы приведут к увеличению времени ожидания!
# make common fields available at root
<<: *common

# ----- Пользовательские модули -----
introduction:
  <<: *common
  introduction_text: |
    Привет!

    Я помогу тебе скачать видео из Instagram.
        
    **Скачать Instagram** /instagram
    Reels и Stories
    
    **Поддержка** /support
    Нужна помощь? Напиши нам в чат.

    Под строкой ввода у вас появилось основное меню. Выберите необходимый функционал и следуйте подсказкам.
  

instagram:
  <<: *common
  command: instagram
  description: Получить сторис/риллс с инстаграм-страницы
  friendly_name: Скачать Instagram
  icon: 📸
  introduction_text: |
    **Скачать Instagram**
    
    __Reels, Stories__
    
    Ниже ты найдешь пример того, как должны выглядеть твои ссылки, чтобы я мог скачать медиа.
    
    **❗Только 1 ссылка за раз!**

    --__Все Stories за 24 часа (анонимно)__--
    `instagram.com/nickname` или `nickname`

    --__Только выбранный Stories__--
    `https://instagram.com/stories/mozgslomal/3007657127355045430?utm_source=ig_story_item_share&igshid=YmMyMTA2M2Y=`

    --__Только выбранный Reels__--
    `https://www.instagram.com/reel/CmrETDDKGLf/?igshid=YmMyMTA2M2Y=`
  pending_text: |
    Начинаю скачивать...
    
    __Это может занять пару минут.__
  result_text: |
    Медиа успешно скачано из аккаунта `@{account}`

    Пришли новую ссылку на **Reels, Stories** или **Аккаунт**, чтобы продолжить скачивание медиа из --Instagram--.

    __Или выйди в основное меню при помощи кнопок в нижнем меню, чтобы скачать медиа из других соцсетей.__

support:
  <<: *common
  command: support
  description: Нужна помощь? Напиши нам в чат
  friendly_name: Поддержка
  icon: 👨‍⚕️
  introduction_text: Нужна помощь? Напиши мне в чат!
  button_contact: Написать в чат
  url_contact: https://t.me/+G--yVAF5Tm82Y2Uy
---