---
# Ш А Б Л О Н
# описание полей см. в README

# имя модуля:
#   <<: *common
#   allowed_role:
#   command:
#   description:
#   friendly_name:
#   icon:
#   introduction_text:
#
#   <<: *csv, <<: *hashtags_editor и т.д. добавлять, если данные фичи есть в модуле

# ----- Общие поля -----
common: &common
  current_module_text: Вы находитесь в модуле {}.
  help_command_text: Для возврата в меню нажмите /start.
  unknown_command_text: Такой команды не существует. Воспользуйся меню под строкой ввода, чтобы попробовать доступный функционал.
  unhandled_error_text: Что-то пошло не так. Но поддержка рядом! /support
  wrong_input_text: Это не похоже на слово.

api_adapter:
  <<: *common
  error_text_account_not_found: Мне не удалось найти этот аккаунт. Проверьте корректность написания никнейма или ссылки и повторите попытку.
  error_text_account_private: К сожалению, аккаунт, который вы отправили на анализ, является закрытым. Я могу анализировать только открытые аккаунты.
  error_text_first_provider_failed: |
      Наблюдаю проблемы с доступом к сервису. 
      Возможно, придется подождать дольше обычного...

trottling:
  <<: *common
  warning_message: |
    Вы отправили слишком много запросов, пожалуйста, подождите.
    Повторные запросы приведут к увеличению времени ожидания!
# make common fields available at root
<<: *common

# ----- Пользовательские модули -----
introduction:
  <<: *common
  introduction_text: |
    Привет!

    Я помогу тебе скачать видео из Instagram.
        
    **Скачать Instagram** /instagram
    Reels и Stories
    
    **Поддержка** /support
    Нужна помощь? Напиши нам в чат.

    Под строкой ввода у вас появилось основное меню. Выберите необходимый функционал и следуйте подсказкам.

support:
  <<: *common
  command: support
  description: Нужна помощь? Напиши нам в чат
  friendly_name: Поддержка
  icon: 👨‍⚕️
  introduction_text: Нужна помощь? Напиши мне в чат!
  button_contact: Написать в чат
  url_contact: https://t.me/datafan
---